# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 27017, host: 6000
  config.vm.provision "shell", path: "provision.sh"
  config.vm.synced_folder "../", "/code"

end
